version: "3.2"

services:
  glitch-princess:
    container_name: glitch-princess 
    image: pendulumchain/pendulum:latest
    build:
      context: .
      dockerfile: dockerfile
      - "30344:1"
      - "8844:1"
      - "30345:1"
      - "9955:1"
    restart: on-failure
    command: ./bin/pendulum-collator --collator -- --execution=wasm  --chain ./specs/rococo-custom-2-raw.json --port 30345 --ws-port 9955 --force-authoring