author = "xiuxiu"
name = "Pendulum"

[[validators]]
args = ["--alice", "--base-path=/tmp/relay/alice"]
bin = "../polkadot/target/release/polkadot"
chain = "./specs/rococo-custom-2-raw.json"
name = "validator_node_alice"
port = 30343
ws_port = 9944

[[validators]]
args = ["--bob", "--base-path=/tmp/relay/bob"]
bin = "../polkadot/target/release/polkadot"
chain = "./specs/rococo-custom-2-raw.json"
name = "validator_node_bob"
port = 30344
ws_port = 9945

[[collators]]
[collators.inner]
args = ["--alice", "--base-path=/tmp/parachain/alice", "--force-authoring", "--enable-offchain-indexing=TRUE"]
bin = "../pendulum/target/release/polkadot"
chain = "./specs/rococo-local-parachain-raw.json"
name = "collator_node"
port = 40333
ws_port = 8844

[collators.relay]
chain = "./specs/rococo-custom-2-raw.json"
port = 30345
ws_port = 9955
