name = "Pendulum"
author = "xiuxiu"

[[validators]]
name = "validator_node"
bin = "./bin/polkadot"
chain = "./specs/rococo-custom-2-raw.json"
args = []
port = 30343
ws_port = 9944

[[collators]]
[collators.inner]
name = "collator_node"
bin = "./bin/pendulum-collator"
chain = "./specs/rococo-local-parachain-raw.json"
args = ["--force-authoring"]
port = 30344
ws_port = 8844

[collators.relay]
chain = "./specs/rococo-custom-2-raw.json"
port = 30345
ws_port = 9955
